# Generated by Django 2.1.2 on 2018-11-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikeuser',
            name='interest_hike',
            field=models.BooleanField(blank=True, null=True, verbose_name='I have led a few hikes before and would like to lead some hikes for the hiking club'),
        ),
        migrations.AddField(
            model_name='hikeuser',
            name='interest_lead',
            field=models.BooleanField(blank=True, null=True, verbose_name="I am 21, have a valid state driver's license, and would like to drive for the club"),
        ),
        migrations.AddField(
            model_name='hikeuser',
            name='school',
            field=models.CharField(choices=[('CC', 'Columbia College'), ('VAN', 'SEAS Undergraduate'), ('TRAIN', 'Barnard College'), ('NONE', 'General Studies'), ('NONE', 'SEAS Graduate'), ('ARTSCIGRAD', 'Graduate School of Arts and Sciences'), ('OTHER', 'Other')], default='CC', max_length=100),
        ),
    ]
