# Generated by Django 2.1.2 on 2018-11-17 05:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181116_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikeuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+17187100555', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hikeuser',
            name='email',
            field=models.EmailField(help_text='Please use a Columbia affiliated email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='hikeuser',
            name='school',
            field=models.CharField(choices=[('CC', 'Columbia College'), ('VAN', 'SEAS Undergraduate'), ('TRAIN', 'Barnard College'), ('NONE', 'General Studies'), ('NONE', 'SEAS Graduate'), ('ARTSCIGRAD', 'Graduate School of Arts and Sciences')], default='CC', max_length=100),
        ),
    ]
