# Generated by Django 2.1.2 on 2018-11-17 14:14

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_hike_signup_limit'),
        ('accounts', '0003_auto_20181117_0535'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hikeuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='hikeuser',
            name='hikes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hikes', to='blog.Hike'),
        ),
    ]
