# Generated by Django 2.1.2 on 2018-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181117_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikeuser',
            name='interest_hike',
        ),
        migrations.AddField(
            model_name='hikeuser',
            name='interest_drive',
            field=models.BooleanField(blank=True, null=True, verbose_name="I am 21, have a valid state driver's license, and would like to drive for the club"),
        ),
        migrations.AlterField(
            model_name='hikeuser',
            name='interest_lead',
            field=models.BooleanField(blank=True, null=True, verbose_name='I have led a few hikes before and would like to lead some hikes for the hiking club'),
        ),
    ]
