# Generated by Django 2.1.2 on 2018-11-18 04:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181117_1450'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hikeuser',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='hikeuser',
            name='school',
            field=models.CharField(choices=[('CC', 'Columbia College'), ('SEAS', 'SEAS Undergraduate'), ('BARN', 'Barnard College'), ('GS', 'General Studies'), ('SEASGRAD', 'SEAS Graduate'), ('ARTSCIGRAD', 'Graduate School of Arts and Sciences')], default='CC', max_length=100),
        ),
    ]
