# Generated by Django 2.1.2 on 2018-11-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hikeuser_medical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hikeuser',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='hikeuser',
            order_with_respect_to='hikes',
        ),
    ]
