# Generated by Django 2.1.2 on 2018-11-02 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_of_hike', models.DateTimeField(verbose_name='date and time of hike')),
                ('travel', models.CharField(choices=[('BUS', 'School Bus'), ('VAN', 'Van'), ('TRAIN', 'Metro North'), ('NONE', 'None')], default='VAN', max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('INTERMEDIATE', 'Intermediate'), ('HARD', 'Hard')], default='EASY', max_length=30)),
            ],
            options={
                'ordering': ('date_of_hike',),
            },
        ),
        migrations.CreateModel(
            name='HikeRequest',
            fields=[
                ('hike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Hike')),
                ('user_who_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('blog.hike',),
        ),
        migrations.AddField(
            model_name='hike',
            name='hike_leaders',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
