# Generated by Django 2.1.2 on 2018-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181027_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ('-on_board', 'last_name')},
        ),
        migrations.AddField(
            model_name='hike',
            name='travel',
            field=models.CharField(choices=[('BUS', 'School Bus'), ('VAN', 'Van'), ('TRAIN', 'Metro North'), ('NONE', 'None')], default='VAN', max_length=200),
        ),
        migrations.AlterField(
            model_name='hike',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('INTERMEDIATE', 'Intermediate'), ('HARD', 'Hard')], default='EASY', max_length=30),
        ),
    ]
