# Generated by Django 2.1.2 on 2018-11-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikerequest',
            name='user_who_requested',
        ),
        migrations.AddField(
            model_name='hikerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hikerequest',
            name='want_to_lead',
            field=models.BooleanField(blank=True, help_text='If you check this box, you will be added to the hike leaders list.', null=True, verbose_name='I want to lead the hike'),
        ),
    ]
