# Generated by Django 2.1.2 on 2018-11-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181114_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikebase',
            name='travel',
            field=models.CharField(choices=[('BUS', 'School Bus'), ('VAN', 'Van'), ('TRAIN', 'Metro North'), ('NONE', 'None')], default='NONE', max_length=200),
        ),
    ]
