# Generated by Django 2.1.2 on 2018-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181117_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='signup_limit',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Hikers limit'),
        ),
    ]
